sample_dbt:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: LAPTOP-118RJ4KP\LOCALDB#9753F992
      # server: localhost
      port: 1433
      database: sample_db1
      schema: sch
      windows_login: True
      trust_cert: True
      
